name: bboiler
description: Приложение управления пивоварней для Raspberry Pi.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc_concurrency: ^0.2.0
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  flutter_gpiod: ^0.5.0
  flutter_switch: ^0.3.2
  freezed_annotation: ^2.2.0
  just_audio: ^0.9.30
  json_annotation: ^4.7.0
  logger: ^1.1.0
  path_provider: ^2.0.11
  syncfusion_flutter_sliders: ^20.3.52
  toggle_switch: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  dart_code_metrics: ^5.0.1
  flutter_lints: ^2.0.1
  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/sound/
